version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: workflow-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fu040913
    ports:
      - "27018:27017"


  backend:
    build:
      context: ../
      dockerfile: ./scripts/Dockerfile-Backend
      args:
        - BUILD_DATE=$(date)
    container_name: workflow-backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    command: [ "sh", "-c", "echo 'Starting Backend...' && python app.py" ]

  frontend:
    build:
      context: ../
      dockerfile: ./scripts/Dockerfile-FrontEnd
      args:
        - BUILD_DATE=$(date)
    container_name: workflow-frontend
    restart: always
    ports:
      - "3000:3000"
    command: ["npm","run","dev"]