version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: workflow-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fu040913
    ports:
      - "27018:27017"